Repository sideeffffect/console-scala-simple, pull requests merged in 2021-03, with the labels that each got.

#56 Update sbt to 1.4.8
  project/build.properties
Labels: dependency-update

#59 Scala 2.13.5
  .scalafix.conf
  build.sbt
  example/src/main/scala/org/eclipse/che/examples/HelloWorld.scala
  project/plugins.sbt
Labels: mergify-merge

#60 Update zio, zio-test, zio-test-sbt to 1.0.5
  project/Dependencies.scala
Labels: type: dependencies

#62 Update sbt-ci-release to 1.5.6
  project/plugins.sbt
Labels: type: dependencies
